config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  resources :guests
  resources :assignments
  root 'rooms#index'
  get 'home/index'
  post 'assignments/new', to: 'assignments#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    validates :room_id, presence:true, uniqueness: true
    validates :guest_id, presence:true, uniqueness: true
    belongs_to :room
    belongs_to :guest
end

app/models/guest.rb
class Guest < ApplicationRecord
    validates :name, presence:true
    validates :phone, presence:true
    has_one :assignment
    has_one :room, through: :assignment
    attribute :assigned, :boolean, default: false
end

app/models/room.rb
class Room < ApplicationRecord
    validates :number, presence:true
    has_one :assignment
    has_one :guest, through: :assignment
    attribute :assigned, :boolean, default: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
    def index
        @guests = Guest.all
    end

    def show
        @guests = Guest.all
    end

    def new
        @guests = Guest.all
    end

    def create
        @assignment = Assignment.new(:room_id => params[:rid], :guest_id => params[:gid])
        respond_to do |format|
            if @assignment.save
              format.html { redirect_to rooms_url, notice: "Assigned" }
              format.json { render :show, status: :created, location: @assignment }
            else
              format.html { render rooms_url, status: :unprocessable_entity}
              format.json { render json: @assignment.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @assignment = Assignment.find(params[:id])
        @assignment.destroy
        respond_to do |format|
          format.html { redirect_to rooms_url, notice: "Unassigned." }
          format.json { head :no_content }
        end
      end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /guests or /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1 or /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: "Guest was successfully created." }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1 or /guests/1.json
  def destroy
    if @guest.room == nil
      @guest.destroy
      respond_to do |format|
        format.html { redirect_to guests_url, notice: "Guest was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to rooms_url, notice: "Check out first." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.require(:guest).permit(:name, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    if @room.guest == nil
      @room.destroy
      respond_to do |format|
        format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to rooms_url, notice: "Check out first." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:number, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/assignments/index.html.erb
<br>
<table class="table table-hover table-striped table-borderless">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
    <% if guest.room == nil %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.phone %></td>
        <td><%= button_to 'Assign', assignments, {:rid => params[:rid],:gid => guest.id} ,class:"btn btn-secondary btn-sm"%> </td>

      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/assignments/new.html.erb
<br>
<table class="table table-hover table-striped table-borderless">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
    <% if guest.room == nil %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.phone %></td>
        <td>
        <%= button_to 'Assign', {:rid => params[:rid], :gid => guest.id}, class:'btn btn-secondary btn-sm' %>
        </td>

      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/assignments/show.html.erb
<br>
<table class="table table-hover table-striped table-borderless">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
    <% if guest.room == nil %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.phone %></td>
        <td><%= button_to 'Assign', assignments, {:rid => params[:rid],:gid => guest.id} ,class:"btn btn-secondary btn-sm"%> </td>

      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/guests/_form.html.erb
<%= form_with(model: guest) do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
        <% guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control"  %>
  </div>
  
  <br />

  <div class="actions">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<br>
<table class="table table-hover table-striped table-borderless">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Assigned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.phone %></td>
        <td>
          <% if guest.room!=nil %>
            <%= guest.room.number %>
          <% else %>
            <%= "unasigned" %>
          <% end %>
        </td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path, class:"btn btn-secondary btn-lg" %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @guest.phone %>
</p>


<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">PMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">



        <% if user_signed_in? %>

          <li class="nav-item">
          <%= link_to 'Rooms', rooms_path, class:'nav-link active' %>
          </li>

          <li class="nav-item">
          <%= link_to 'Guests', guests_path, class:'nav-link active' %>
          </li>

          <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link active' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, class:'nav-link active' %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:'nav-link active' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:'nav-link active' %>
          </li>
        <% end %>


      </ul>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>PMS</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
        <br/>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br />
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :number %>
    <%= form.text_field :number, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  
  <br />

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<br>
<table class="table table-hover table-striped table-borderless">
  <thead class="table-dark">
    <tr>
      <th>Number</th>
      <th>Description</th>
      <th>Assigned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.description %></td>
        <td>
          <% if room.guest!=nil %>
            <%= room.guest.name %>
            <%= link_to 'Check Out', assignment_path(room.assignment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            <%= link_to "unassigned", new_assignment_path(:rid => room.id)  %>
          <% end %>
        </td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to ' New Room ', new_room_path, class:"btn btn-secondary" %>
<br><br>

app/views/rooms/new.html.erb
<br/>
<h1>New Room</h1>

<%= render 'form', room: @room %>
<br />
<%= link_to 'Back', rooms_path, class:'btn btn-dark' %>

app/views/rooms/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @room.number %></h5>
    <p class="card-text"><%= @room.description %></p>
    <%= link_to 'Edit', edit_room_path(@room), class:"btn btn-secondary" %>
    <%= link_to 'Back', rooms_path, class:"btn btn-secondary" %>
  </div>
</div>